version: '3.9'

services:
  mongo_db: 
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    container_name: server-api
    build: ./
    command: npm run dev
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    environment: 
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_database
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}